import { CasesData } from './caseCardsTypes';

export const casesData: CasesData = [
   {
      id: '0001',
      type: 'EVENT',
      title: 'МТС',
      description: 'Музыкальное шоу «Blog&VOICE»',
      link: '/cases/mts-blog-and-voice',
      image: '/images/cases/01.webp',
      prevNextLinks: {
         prev: '/cases/solid-bank/',
         next: '/cases/mts-30-let/',
      },
   },
   {
      id: '0002',
      type: 'EVENT',
      title: 'MTC',
      description: '30 лет. Больше чем цифра',
      link: '/cases/mts-30-let/',
      image: '/images/cases/12.webp',
      prevNextLinks: {
         prev: '/cases/mts-blog-and-voice',
         next: '/cases/gazpromneft-innovacii/',
      },
   },
   {
      id: '0003',
      type: 'EVENT',
      title: 'Газпром<wbr/>нефть Инновации',
      description: 'Корпоративное мероприятие',
      link: '/cases/gazpromneft-innovacii/',
      image: '/images/cases/11.webp',
      prevNextLinks: {
         prev: '/cases/mts-30-let/',
         next: '/cases/tele2/',
      },
   },
   {
      id: '0004',
      type: 'EVENT',
      title: 'TELE2',
      description: 'Корпоративное мероприятие',
      link: '/cases/tele2/',
      image: '/images/cases/26.webp',
      prevNextLinks: {
         prev: '/cases/gazpromneft-innovacii/',
         next: '/cases/rosselhozbank-2/',
      },
   },
   {
      id: '0005',
      type: 'EVENT',
      title: 'Россельхоз<wbr/>банк',
      description: 'Открытия отделений банка',
      link: '/cases/rosselhozbank-2/',
      image: '/images/cases/24.webp',
      prevNextLinks: {
         prev: '/cases/tele2/',
         next: '/cases/rosselhozbank/',
      },
   },
   {
      id: '0006',
      type: 'EVENT',
      title: 'Россельхоз<wbr/>банк',
      description: 'Мероприятие для партнеров',
      link: '/cases/rosselhozbank/',
      image: '/images/cases/23.webp',
      prevNextLinks: {
         prev: '/cases/rosselhozbank-2/',
         next: '/cases/gloria-jeans',
      },
   },
   {
      id: '0007',
      type: 'EVENT',
      title: 'Gloria Jeans',
      description: 'Открытия магазинов',
      link: '/cases/gloria-jeans',
      image: '/images/cases/06.webp',
      prevNextLinks: {
         prev: '/cases/rosselhozbank/',
         next: '/cases/alfabank/',
      },
   },
   {
      id: '0008',
      type: 'EVENT',
      title: 'Альфа<wbr/>банк',
      description: 'Открытие отделений',
      link: '/cases/alfabank/',
      image: '/images/cases/15.webp',
      prevNextLinks: {
         prev: '/cases/gloria-jeans',
         next: '/cases/sovkombank/',
      },
   },
   {
      id: '0009',
      type: 'EVENT',
      title: 'Совком<wbr/>банк',
      description: 'Открытие отделений',
      link: '/cases/sovkombank/',
      image: '/images/cases/25.webp',
      prevNextLinks: {
         prev: '/cases/alfabank/',
         next: '/cases/komandor/',
      },
   },
   {
      id: '0010',
      type: 'EVENT',
      title: 'Командор',
      description: 'Открытие сети магазинов',
      link: '/cases/komandor/',
      image: '/images/cases/20.webp',
      prevNextLinks: {
         prev: '/cases/sovkombank/',
         next: '/cases/zhiznmart',
      },
   },
   {
      id: '0011',
      type: 'EVENT',
      title: 'ЖизньМарт',
      description: 'Открытия магазинов',
      link: '/cases/zhiznmart',
      image: '/images/cases/07.webp',
      prevNextLinks: {
         prev: '/cases/komandor/',
         next: '/cases/kari/',
      },
   },
   {
      id: '0012',
      type: 'EVENT',
      title: 'Kari',
      description: 'Фестиваль шопинга',
      link: '/cases/kari/',
      image: '/images/cases/13.webp',
      prevNextLinks: {
         prev: '/cases/zhiznmart',
         next: '/cases/megafon/',
      },
   },
   {
      id: '0013',
      type: 'PR',
      title: 'Мегафон',
      description: 'PR-мероприятия',
      link: '/cases/megafon/',
      image: '/images/cases/21.webp',
      prevNextLinks: {
         prev: '/cases/kari/',
         next: '/cases/rzhd/',
      },
   },
   {
      id: '0014',
      type: 'PR',
      title: 'РЖД',
      description: 'Слет молодежи',
      link: '/cases/rzhd/',
      image: '/images/cases/14.webp',
      prevNextLinks: {
         prev: '/cases/megafon/',
         next: '/cases/razumnye-ot-naroda',
      },
   },
   {
      id: '0015',
      type: 'PR',
      title: 'Разумные от народа',
      description: 'Организация конференции',
      link: '/cases/razumnye-ot-naroda',
      image: '/images/cases/08.webp',
      prevNextLinks: {
         prev: '/cases/rzhd/',
         next: '/cases/red-bull/',
      },
   },
   {
      id: '0016',
      type: 'PR',
      title: 'Red bull',
      description: 'Реализация ряда мероприятий',
      link: '/cases/red-bull/',
      image: '/images/cases/22.webp',
      prevNextLinks: {
         prev: '/cases/razumnye-ot-naroda',
         next: '/cases/tnt',
      },
   },
   {
      id: '0017',
      type: 'PR',
      title: 'ТНТ',
      description: 'Запуск рекламных кампаний',
      link: '/cases/tnt',
      image: '/images/cases/09.webp',
      prevNextLinks: {
         prev: '/cases/red-bull/',
         next: '/cases/eastern-special-equipment',
      },
   },
   {
      id: '0018',
      type: 'PR',
      title: 'Восточная техника',
      description: 'Присутствие бренда на выставке',
      link: '/cases/eastern-special-equipment',
      image: '/images/cases/05.webp',
      prevNextLinks: {
         prev: '/cases/tnt',
         next: '/cases/jagermaster/',
      },
   },
   {
      id: '0019',
      type: 'BTL',
      title: 'Jager<wbr/>meister',
      description: 'Проведение дегустаций',
      link: '/cases/jagermaster/',
      image: '/images/cases/19.webp',
      prevNextLinks: {
         prev: '/cases/eastern-special-equipment',
         next: '/cases/bochkarev/',
      },
   },
   {
      id: '0020',
      type: 'BTL',
      title: 'Бочкарев',
      description: 'Дегустации',
      link: '/cases/bochkarev/',
      image: '/images/cases/16.webp',
      prevNextLinks: {
         prev: '/cases/jagermaster/',
         next: '/cases/za-rodinu/',
      },
   },
   {
      id: '0021',
      type: 'BTL',
      title: 'За Родину',
      description: 'Анкетирование покупателей',
      link: '/cases/za-rodinu/',
      image: '/images/cases/27.webp',
      prevNextLinks: {
         prev: '/cases/bochkarev/',
         next: '/cases/burger-king/',
      },
   },
   {
      id: '0022',
      type: 'BTL',
      title: 'Бургер Кинг',
      description: 'Промоакции',
      link: '/cases/burger-king/',
      image: '/images/cases/17.webp',
      prevNextLinks: {
         prev: '/cases/za-rodinu/',
         next: '/cases/heineken/',
      },
   },
   {
      id: '0023',
      type: 'BTL',
      title: 'Heineken',
      description: 'Дегустация безалкогольных напитков',
      link: '/cases/heineken/',
      image: '/images/cases/18.webp',
      prevNextLinks: {
         prev: '/cases/burger-king/',
         next: '/cases/glazka/',
      },
   },
   {
      id: '0024',
      type: 'EVENT',
      title: 'Глазка',
      description: '15 лет — юбилей!',
      link: '/cases/glazka/',
      image: '/images/cases/28.webp',
      prevNextLinks: {
         prev: '/cases/heineken/',
         next: '/cases/trakresurs/',
      },
   },
   {
      id: '0025',
      type: 'EVENT',
      title: 'Тракресурс',
      description: 'День рождения филиала',
      link: '/cases/trakresurs/',
      image: '/images/cases/29.webp',
      prevNextLinks: {
         prev: '/cases/glazka/',
         next: '/cases/novie-metallurgicheskie-tehnologii/',
      },
   },
   {
      id: '0026',
      type: 'EVENT',
      title: 'Новые металлур<wbr/>гические технологии',
      description: '10-летие компании',
      link: '/cases/novie-metallurgicheskie-tehnologii/',
      image: '/images/cases/30.webp',
      prevNextLinks: {
         prev: '/cases/trakresurs/',
         next: '/cases/haval-novosibirsk/',
      },
   },
   {
      id: '0027',
      type: 'EVENT',
      title: 'HAVAL',
      description: 'Бренд-день в Новосибирске',
      link: '/cases/haval-novosibirsk/',
      image: '/images/cases/39.webp',
      prevNextLinks: {
         prev: '/cases/novie-metallurgicheskie-tehnologii/',
         next: '/cases/haval-samara/',
      },
   },
   {
      id: '0028',
      type: 'EVENT',
      title: 'HAVAL',
      description: 'Бренд-день в Самаре',
      link: '/cases/haval-samara/',
      image: '/images/cases/40.webp',
      prevNextLinks: {
         prev: '/cases/haval-novosibirsk/',
         next: '/cases/magnit/',
      },
   },
   {
      id: '0029',
      type: 'BTL',
      title: 'Магнит',
      description: 'Открытие магазина',
      link: '/cases/magnit/',
      image: '/images/cases/41.webp',
      prevNextLinks: {
         prev: '/cases/haval-samara/',
         next: '/cases/oktoprint/',
      },
   },
   {
      id: '0030',
      type: 'EVENT',
      title: 'ОктоПринт',
      description: 'Полиграфический семинар для бренда',
      link: '/cases/oktoprint/',
      image: '/images/cases/42.webp',
      prevNextLinks: {
         prev: '/cases/magnit/',
         next: '/cases/solid-bank/',
      },
   },
   {
      id: '0031',
      type: 'BTL',
      title: 'Солид Банк',
      description: 'Открытие первого отделения',
      link: '/cases/solid-bank/',
      image: '/images/cases/43.webp',
      prevNextLinks: {
         prev: '/cases/oktoprint/',
         next: '/cases/mts-blog-and-voice',
      },
   },
];
